language: go

env:
  - GO111MODULE=on

go:
  - "1.14.x"
  - "1.15.x"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go mod vendor
  - make
  - make gen
  - go test -v -mod vendor -race -cover -timeout=2m ./...
  - go test -v -mod vendor -race -cover -timeout=2m -tags=tinygo ./...
